services:
  shortn:
    build:
      context: .
    container_name: shortn
    ports:
      - "49152:49152"
    volumes:
      - ./src:/app/src
    environment:
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 49152
    command: sh -c "python /app/src/manage_users.py init && flask run"
networks:
  shortn-network:
    driver: bridge